# Generated by Django 4.2 on 2023-05-08 22:35

from django.db import migrations, models
import exports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('file', models.FileField(blank=True, null=True, upload_to=exports.models.export_file_handler)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Export',
                'verbose_name_plural': 'Exports',
            },
        ),
    ]
