# Generated by Django 4.2 on 2023-05-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, unique=True)),
                ("overview", models.TextField()),
                ("release_date", models.DateField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("rating_last_updated", models.DateTimeField(blank=True, null=True)),
                ("rating_count", models.IntegerField(blank=True, null=True)),
                (
                    "rating_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "idx",
                    models.IntegerField(
                        blank=True, help_text="Position IDs for ML", null=True
                    ),
                ),
            ],
        ),
    ]
