# Generated by Django 4.2 on 2023-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
